<?php

namespace App\Support;

/**
 * Portfolio / sample-work content (visualization renders, permit sets, Revit + scan-to-BIM sheets,
 * case-study media). Image files live in public/assets/img/work/ and are generated by
 * tools/build-work-assets.mjs, which also writes resources/data/work-manifest.json (pixel sizes).
 *
 * PRIVACY NOTE: sheets are published cropped/redacted (no owner names, addresses, contractor details
 * or client logos) and cover sheets / site plans are intentionally omitted.
 */
class Portfolio
{
    private static ?array $manifest = null;

    /** Resolve an image key (e.g. "viz/bedroom") to URLs + sizes. Thumb = 800w variant. */
    public static function img(string $key): array
    {
        if (self::$manifest === null) {
            $file = resource_path('data/work-manifest.json');
            self::$manifest = is_file($file) ? (json_decode(file_get_contents($file), true) ?: []) : [];
        }
        $m = self::$manifest["{$key}"] ?? ['w' => 1600, 'h' => 1000, 'tw' => 800, 'th' => 500];

        return [
            'key'   => $key,
            'src'   => asset_v("assets/img/work/{$key}.webp"),
            'thumb' => asset_v("assets/img/work/{$key}-800.webp"),
            'base'  => "assets/img/work/{$key}",           // for partials that expect "<base>.webp" / "<base>-800.webp"
            'w'     => $m['w'], 'h' => $m['h'], 'tw' => $m['tw'], 'th' => $m['th'],
        ];
    }

    /* ------------------------------------------------------------------ Visualization gallery */

    public static function vizCategories(): array
    {
        return ['interiors' => 'Interiors', 'exteriors' => 'Exteriors', 'floorplans' => '3D floor plans', 'booth' => 'Booth design', 'storage' => 'Self-storage containers'];
    }

    public static function viz(): array
    {
        $items = [
            ['viz/bandon-dusk-lawn',     'exteriors',  'Rural residence at dusk',            'Dark timber-and-stone residence with warm interior lighting at dusk, set among tall pines', '50% 50%'],
            ['viz/bandon-dusk-wrap',     'exteriors',  'Wraparound porch residence',         'Two-storey residence with a wraparound timber porch glowing at dusk', '50% 50%'],
            ['viz/bandon-night-black',   'exteriors',  'Evening front elevation',            'Black-clad residence with lit windows and a stone chimney against a dusk sky', '50% 50%'],
            ['viz/brick-mixed-use',      'exteriors',  'Brick mixed-use building',           'Three-storey red-brick building with ground-floor shopfronts seen from the street', '50% 50%'],
            ['viz/commercial-options',   'exteriors',  'Commercial building options',        'Commercial office building shown from three camera positions with cars in the foreground', '50% 40%'],
            ['viz/bungalow-front',       'exteriors',  'Single-storey residence',            'White single-storey residence with a dark roof, landscaping and a car on the driveway', '50% 50%'],
            ['viz/house-portrait',       'exteriors',  'Gabled family home',                 'Blue clapboard family home with a gabled entrance, garden planting and cobbled drive', '50% 35%'],
            ['viz/bedroom',              'interiors',  'Primary bedroom',                    'Bright bedroom interior with timber flooring, panelled wall and floor-to-ceiling curtains', '50% 55%'],
            ['viz/dining-room',          'interiors',  'Open kitchen and dining',            'Open-plan dining area with green velvet chairs, a long table and a white kitchen beyond', '50% 55%'],
            ['viz/kitchen-dining',       'interiors',  'Kitchen and dining area',            'Modern kitchen with timber and white cabinetry and a round dining table', '50% 50%'],
            ['viz/lounge',               'interiors',  'Lounge with feature ceiling',        'Lounge with a curved sofa, timber slat walls and a circular recessed ceiling feature', '50% 50%'],
            ['viz/kitchen-plan',         'interiors',  'Kitchen render beside its plan',     'Kitchen render with island and tall cabinets shown beside the plan and elevation drawings', '40% 50%'],
            ['viz/floorplan-3d-retail',  'floorplans', '3D floor plan, axonometric',        'Axonometric 3D floor plan of a large open space with furniture, fixtures and timber flooring', '50% 50%'],
            ['viz/floorplan-3d-top',     'floorplans', '3D floor plan, top view',           'Top-down 3D floor plan with herringbone flooring, blue rugs and furniture layout', '50% 50%'],
            ['viz/floorplan-iso',        'floorplans', '3D floor plan, isometric',          'Isometric cutaway 3D floor plan of an irregular-shaped commercial space', '50% 50%'],
            ['viz/storage-unit-iso',           'storage', 'Self-storage unit, isometric',   'Isometric cutaway view of a furnished self-storage unit interior with boxes, furniture and luggage', '50% 50%'],
            ['viz/storage-container-top',      'storage', '3D floor plan, storage container', 'Top-down cutaway view of a storage container interior with furniture, boxes and bags', '50% 50%'],
            ['viz/storage-container-angle',    'storage', 'Storage container, angled view', 'Angled cutaway view of the same storage container interior with furniture and boxes', '50% 50%'],
            ['viz/site-aerial',          'exteriors',    'Aerial site visualization',         'Aerial view of a row of houses with landscaping on a green site beside a road', '50% 50%'],
            ['viz/booth-concept',        'booth',    'Exhibition booth concept',          'Exhibition booth concept with a pink-striped container, canopy and an illuminated brand tower (brand placeholder)', '50% 40%'],
        ];

        return array_map(fn ($i) => self::img($i[0]) + ['cat' => $i[1], 'title' => $i[2], 'alt' => $i[3], 'pos' => $i[4]], $items);
    }

    /**
     * Flat image list + category labels for a service page's showcase carousel.
     * group: visualization (renders) | bim | cad (sample-set sheets).
     */
    public static function showcase(string $category): array
    {
        if ($category === 'visualization') {
            return ['images' => self::viz(), 'cats' => self::vizCategories()];
        }

        $images = [];
        $cats = [];
        foreach (self::sets($category) as $id => $s) {
            $cats[$id] = $s['place'];
            foreach ($s['sheets'] as $sh) {
                $images[] = $sh + ['cat' => $id];
            }
        }

        return ['images' => $images, 'cats' => $cats];
    }

    /**
     * Curated, clear samples for the auto-running reels (home + service pages).
     * Every entry: src, thumb, w, h, tw, th, alt, title, sheet (true = drawing sheet / white-background view).
     */
    public static function reel(string $category, int $limit = 12): array
    {
        $out = [];

        if ($category === 'visualization') {
            // round-robin across the categories so every kind of work (interior, exterior, 3D plans, booth, storage) shows early
            $byCat = [];
            foreach (self::viz() as $i) {
                $byCat[$i['cat']][] = $i;
            }
            while (count($out) < $limit && array_filter($byCat)) {
                foreach ($byCat as $c => $list) {
                    if ($list && count($out) < $limit) {
                        $out[] = array_shift($byCat[$c]) + ['sheet' => false];
                    }
                }
            }

            return $out;
        }

        if ($category === 'bim') {
            $picks = [
                ['scan/house-1-model', 'Revit existing-conditions model built from a surveyor point cloud', 'Revit model from point cloud', false],
                ['scan/house-1-cloud', 'Point cloud of a historic brick house captured by a surveyor', 'Surveyor point cloud', false],
                ['cases/manuel-house-3d', 'Revit 3D view of a double-storey house', 'Revit 3D view', true],
                ['scan/house-2-model', 'Revit model close-up of a house front, chimneys and entrance', 'Revit model detail', false],
                ['scan/facade-model', 'Revit model of a street facade with carved entrance details modeled', 'Revit facade model', false],
            ];
            foreach ($picks as [$key, $alt, $title, $sheet]) {
                $out[] = self::img($key) + ['alt' => $alt, 'title' => $title, 'sheet' => $sheet];
            }
            foreach (self::sets('bim') as $s) {
                foreach (array_slice($s['sheets'], 0, 2) as $sh) {
                    $out[] = $sh + ['sheet' => true];
                }
            }

            return array_slice($out, 0, $limit);
        }

        // drawing sets: round-robin so every set (NY, CA, VA ...) is represented early
        $bySet = [];
        foreach (self::sets($category) as $id => $s) {
            $bySet[$id] = $s['sheets'];
        }
        while (count($out) < $limit && array_filter($bySet)) {
            foreach ($bySet as $id => $list) {
                if ($list && count($out) < $limit) {
                    $out[] = array_shift($bySet[$id]) + ['sheet' => true];
                }
            }
        }

        return $out;
    }

    /* ------------------------------------------------------------------ Drawing / model sample sets */

    /**
     * group: cad (permit sets) | bim (Revit + scan-to-BIM).
     * `total` = sheets in the full set; `sheets` = the (redacted) sample sheets published here.
     */
    public static function sets(string $group): array
    {
        $all = [
            'ny' => ['group' => 'cad', 'title' => 'Residential Addition Permit Set', 'place' => 'New York, USA', 'total' => 9,
                'summary' => 'Addition to an existing house: main level plan, roof plan, elevations, section and construction details.',
                'chips' => ['Floor plan', 'Roof plan', 'Elevations', 'Section', 'Details'],
                'sheets' => [['01-main-level-plan', 'A1.1', 'Main level plan'], ['02-roof-plan', 'A1.3', 'Roof plan'], ['03-elevations-front-back', 'A2.1', 'Exterior elevations: front and back'],
                    ['04-elevations-right-left', 'A2.2', 'Exterior elevations: right and left'], ['05-building-section', 'A2.3', 'Building section'], ['06-architectural-details', 'A5.1', 'Architectural details'], ['07-door-window-details', 'A6.2', 'Door and window details']]],
            'caa' => ['group' => 'cad', 'title' => 'Residential Addition Permit Set', 'place' => 'California, USA', 'total' => 7,
                'summary' => 'Bedroom and bath addition: floor plan with schedules, roof plan, elevations and electrical plan.',
                'chips' => ['Floor plan', 'Schedules', 'Elevations', 'Electrical'],
                'sheets' => [['01-main-floor-plan', 'A1.1', 'Main floor plan with schedules'], ['02-roof-plan', 'A1.2', 'Roof plan'], ['03-elevations-left-right', 'A2.1', 'Elevations: left and right'],
                    ['04-elevations-front-back', 'A2.2', 'Elevations: front and back'], ['05-electrical-plan', 'E1.2', 'Main level electrical plan']]],
            'car' => ['group' => 'cad', 'title' => 'Residential Remodel Permit Set', 'place' => 'California, USA', 'total' => 7,
                'summary' => 'Whole-house remodel: proposed main level plan with door and window schedules, roof plan, elevations and kitchen layout.',
                'chips' => ['Proposed plan', 'Schedules', 'Elevations', 'Kitchen layout'],
                'sheets' => [['01-proposed-main-level-plan', 'A2.2', 'Proposed main level plan'], ['02-roof-plan', 'A1.3', 'Roof plan'], ['03-elevations-left-front', 'A2.3', 'Elevations: left and front'],
                    ['04-elevations-right-back', 'A2.4', 'Elevations: right and back'], ['05-kitchen-plan-elevation', 'A2.5', 'Kitchen plan and interior elevation']]],
            'va' => ['group' => 'cad', 'title' => 'Sunroom Addition Permit Drawings', 'place' => 'Virginia, USA', 'total' => 3,
                'summary' => 'Sunroom and paver-patio addition to an existing home: plan, roof plan and exterior elevations with schedules and notes.',
                'chips' => ['Plan', 'Roof plan', 'Elevations', 'Schedules'],
                'sheets' => [['01-main-level-plan', 'A1', 'Main level plan'], ['02-roof-plan', 'A2', 'Roof plan'], ['03-exterior-elevations', 'A3', 'Exterior elevations']]],
            'vt' => ['group' => 'bim', 'title' => 'Commercial Scan-to-BIM Existing Conditions', 'place' => 'Vermont, USA', 'total' => 19,
                'summary' => 'Existing-conditions Revit drawing set from registered scan data: floor plans, exterior elevations and building sections.',
                'chips' => ['Existing conditions drawings', 'Point cloud', 'MEP photo documentation'],
                'sheets' => [['01-level-1-floor-plan', 'A103', 'Level 1 floor plan'], ['02-level-2-floor-plan', 'A104', 'Level 2 floor plan'], ['03-exterior-elevations', 'A115', 'Exterior elevations'], ['04-building-sections', 'A117', 'Building sections']]],
            'pa' => ['group' => 'bim', 'title' => 'Residential Scan-to-BIM Existing Conditions', 'place' => 'Pennsylvania, USA', 'total' => 7,
                'summary' => 'Existing-conditions drawings for a large residence: basement and floor plans plus all four exterior elevations.',
                'chips' => ['Existing conditions drawings', 'Point cloud', 'MEP photo documentation'],
                'sheets' => [['01-level-1-floor-plan', 'A103', 'Level 1 floor plan'], ['02-basement-floor-plan', 'A102', 'Basement floor plan'], ['03-level-2-floor-plan', 'A104', 'Level 2 floor plan'], ['04-exterior-elevations', 'A106', 'Exterior elevations']]],
            'az' => ['group' => 'bim', 'title' => 'Commercial Revit Existing Conditions', 'place' => 'Arizona, USA', 'total' => 7,
                'summary' => 'Multi-level commercial building documented in Revit: basement, level 1 and level 2 plans and building sections.',
                'chips' => ['Floor plans', 'Building sections', 'Existing conditions'],
                'sheets' => [['01-level-1-floor-plan', 'A102', 'Level 1 floor plan'], ['02-level-2-floor-plan', 'A103', 'Level 2 floor plan'], ['03-basement-floor-plan', 'A101', 'Basement floor plan'], ['04-building-sections', 'A107', 'Building sections']]],
        ];

        $out = [];
        foreach ($all as $id => $s) {
            if ($s['group'] !== $group) {
                continue;
            }
            $s['id'] = $id;
            $s['sheets'] = array_map(function ($sh) use ($id, $s) {
                return self::img("sets/{$id}/{$sh[0]}") + [
                    'no'    => $sh[1],
                    'title' => $sh[2],
                    'alt'   => "Sheet {$sh[1]}: {$sh[2]} from a {$s['place']} " . strtolower($s['title']),
                ];
            }, $s['sheets']);
            $out[$id] = $s;
        }

        return $out;
    }

    /* ------------------------------------------------------------------ Scan-to-BIM before / after */

    public static function scanPairs(): array
    {
        $mk = fn ($key, $ratio, $label, $altA, $altB) => [
            'label' => $label, 'ratio' => $ratio, 'a' => self::img("scan/{$key}-cloud"), 'b' => self::img("scan/{$key}-model"), 'altA' => $altA, 'altB' => $altB,
        ];

        return [
            $mk('house-1', '1600 / 1000', 'View 1: site', 'Coloured point cloud of a historic brick house and its grounds', 'Revit existing-conditions model of the same house and grounds'),
            $mk('house-2', '730 / 330', 'View 2: detail', 'Point cloud close-up of the house front, chimneys and entrance', 'Revit model close-up of the same house front, chimneys and entrance'),
        ];
    }

    public static function scanFacade(): array
    {
        return ['a' => self::img('scan/facade-cloud'), 'b' => self::img('scan/facade-model'),
            'altA' => 'Point cloud of a street facade with carved stone entrance details', 'altB' => 'Revit model of the same street facade with the entrance details modeled'];
    }

    /* ------------------------------------------------------------------ Case-study media */

    /** Media for /collaborations/{slug}/ pages and the collaboration cards. */
    public static function caseMedia(string $slug): array
    {
        $media = [
            'uk-3d-floor-plans-smart-heating-cooling' => [
                'cover'   => self::img('cases/uk-floorplan-ground'),
                'alt'     => 'Top-down 3D floor plan of a commercial building showing walls, openings and internal layout',
                'caption' => 'Commercial 3D floor plan',
                'gallery_title' => '3D floor plans',
                'gallery' => self::gallery([
                    ['uk-floorplan-ground', 'Ground floor', 'Top-down 3D floor plan of a large commercial ground floor with offices, meeting rooms and a central courtyard'],
                    ['uk-floorplan-b301-03', 'Courtyard block, typical floor', 'Top-down 3D floor plan of a courtyard-style accommodation block with furnished rooms and bathrooms'],
                    ['uk-floorplan-b301-05', 'U-shaped block, upper floor', 'Top-down 3D floor plan of a U-shaped accommodation block with furnished rooms and corridors'],
                    ['uk-floorplan-topdown', 'Mixed-use floor with terraces', 'Top-down 3D floor plan of a long mixed-use floor with rooms, shared spaces and green terraces'],
                ]),
            ],
            'fifa-2026-circulation-plan-drafting' => [
                'cover'   => self::img('cases/fifa-three-level-circulation'),
                'alt'     => 'Three-level 2D circulation plan study showing movement and access across a large venue',
                'caption' => 'Three-level circulation plan study',
            ],
            'manuel-development-revit-support' => [
                'cover'   => self::img('cases/manuel-house-3d'),
                'alt'     => 'Revit 3D view of a two-storey house with a timber-brown roof and double garage',
                'caption' => 'Revit model of a double-storey house',
                'video'   => [
                    'src'    => asset('assets/video/revit-model-walkthrough.mp4'),
                    'poster' => asset('assets/video/revit-model-walkthrough-poster.webp'),
                    'title'  => 'Revit model update walkthrough',
                ],
                'sheets'  => array_map(fn ($sh) => self::img("sets/manuel/{$sh[0]}") + ['no' => $sh[1], 'title' => $sh[2],
                    'alt' => "Sheet {$sh[1]}: {$sh[2]} from the double-storey house drawing set"], [
                    ['01-front-elevation', 'A101', 'Front elevation'], ['02-basement-floor-plan', 'A105', 'Basement floor plan'], ['03-main-floor-plan', 'A106', 'Main floor plan'],
                    ['04-upper-floor-plan', 'A107', 'Upper floor plan'], ['05-building-section-a-a', 'A108', 'Building section A-A'], ['06-building-section-b-b', 'A109', 'Building section B-B']]),
            ],
            'texas-ongoing-visualization-support' => [
                'cover'   => self::img('cases/texas-hall-staircase'),
                'alt'     => 'Photorealistic interior rendering of an entrance hall with a crystal chandelier, panelled walls and a marble floor',
                'caption' => 'Interior rendering: entrance hall',
                'gallery_title' => 'Renderings',
                'gallery' => self::gallery([
                    ['texas-hall-staircase', 'Entrance hall', 'Photorealistic rendering of an entrance hall with a staircase, chandelier and marble floor'],
                    ['texas-living-blue', 'Living room', 'Photorealistic rendering of a living room with a blue velvet sofa, curtains and an arched floor lamp'],
                    ['texas-bedroom', 'Bedroom', 'Photorealistic rendering of a bedroom with a textured feature wall, upholstered bed and framed artwork'],
                    ['texas-fireplace-hall', 'Double-height lounge', 'Photorealistic rendering of a double-height lounge with two leather armchairs in front of a fireplace'],
                    ['texas-kitchen', 'Kitchen detail', 'Photorealistic close-up rendering of a kitchen with a terrazzo worktop, tiled splashback and warm under-cabinet lighting'],
                ]),
            ],
        ];

        return $media[$slug] ?? [];
    }

    /** Gallery items for a case study: [file name, title, alt text]. Files live in assets/img/work/cases. */
    private static function gallery(array $items): array
    {
        return array_map(fn ($i) => self::img('cases/' . $i[0]) + ['title' => $i[1], 'alt' => $i[2]], $items);
    }

    /** A handful of the strongest pieces for the homepage "Selected work" mosaic. */
    public static function highlights(): array
    {
        $viz = collect(self::viz())->keyBy('key');

        return [
            ['img' => $viz['viz/bandon-dusk-wrap'], 'tag' => 'Visualization', 'title' => 'Exterior at dusk', 'url' => 'services.visualization', 'size' => 'lg'],
            ['img' => $viz['viz/kitchen-dining'],   'tag' => 'Visualization', 'title' => 'Kitchen interior', 'url' => 'services.visualization', 'size' => 'sm'],
            ['img' => self::img('sets/ny/01-main-level-plan'), 'tag' => 'CAD and permit', 'title' => 'Permit set floor plan', 'url' => 'services.cad', 'size' => 'sm', 'alt' => 'Main level floor plan from a residential addition permit set'],
            ['img' => $viz['viz/floorplan-3d-top'], 'tag' => 'Visualization', 'title' => '3D floor plan', 'url' => 'services.visualization', 'size' => 'sm'],
            ['img' => self::img('scan/house-1-model'), 'tag' => 'BIM and Revit', 'title' => 'Scan to BIM model', 'url' => 'services.bim', 'size' => 'lg', 'alt' => 'Revit existing-conditions model of a historic brick house built from a point cloud'],
        ];
    }
}
